[build]
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_846meoc"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_vjj22lq"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "623nyBirJFx7iuR6Q"
